name: Build and Run Docker Image

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
   runs-on: [self-hosted, wisecow]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build the Docker image
      run: |
        docker build -t pratikphanase97/wisecow:latest .

    - name: Push the Docker image to DockerHub
      run: |
        docker push pratikphanase97/wisecow:latest

    - name: Run the Docker image on remote host
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ env.EC2_HOST }} \
          "docker pull pratikphanase97/wisecow:latest && \
           docker run -d -p 4499:4499 pratikphanase97/wisecow:latest"
